#!/bin/bash

#SBATCH --job-name="IFI-case_2"     # Job name
#SBATCH --output=job.%j.out        # Name of stdout output file (%j expands to jobId)
#SBATCH --time=4-00:00:00          # time limit, 4 days, for this job.  
#SBATCH --partition=sm            # select partition or queue 
#SBATCH --ntasks=1                 # requested number of cpus (precedes --ntasks-per-node)
#SBATCH --cpus-per-task=40         # number of threads per task; so if ntasks=1, then total number of cpus allocated will be 1*40

cd $SLURM_SUBMIT_DIR               # change your working directory where you launch your job.
srun ./pic_1d